
require("dotenv").config();
const express=require("express"),cors=require("cors"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),fs=require("fs"),path=require("path"),crypto=require("crypto"),multer=require("multer");
const app=express(),PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET||"change-this-secret",OPENAI_API_KEY=process.env.OPENAI_API_KEY||"",OPENAI_MODEL=process.env.OPENAI_MODEL||"gpt-4.1-mini";
const DB_PATH=path.join(__dirname,"data","db.json"),UPLOAD_DIR=path.join(__dirname,"data","uploads"),upload=multer({dest:UPLOAD_DIR});
app.use(cors());app.use(express.json({limit:"10mb"}));app.use(express.static(path.join(__dirname,"public")));
function id(){return crypto.randomUUID?crypto.randomUUID():crypto.randomBytes(16).toString("hex")}
function ensureDb(){if(!fs.existsSync(path.dirname(DB_PATH)))fs.mkdirSync(path.dirname(DB_PATH),{recursive:true});if(!fs.existsSync(UPLOAD_DIR))fs.mkdirSync(UPLOAD_DIR,{recursive:true});if(!fs.existsSync(DB_PATH))fs.writeFileSync(DB_PATH,JSON.stringify({users:[],chats:[],progress:[],plans:[],quizzes:[],flashcards:[],uploads:[],memories:[],classes:[],payments:[]},null,2))}
function readDb(){ensureDb();try{const db=JSON.parse(fs.readFileSync(DB_PATH,"utf8"));["users","chats","progress","plans","quizzes","flashcards","uploads","memories","classes","payments"].forEach(k=>db[k]||=[]);return db}catch{return{users:[],chats:[],progress:[],plans:[],quizzes:[],flashcards:[],uploads:[],memories:[],classes:[],payments:[]}}}
function writeDb(db){fs.writeFileSync(DB_PATH,JSON.stringify(db,null,2))}
function safeUser(u){if(!u)return null;const{passwordHash,...s}=u;return s}
function tokenFor(u){return jwt.sign({id:u.id,email:u.email},JWT_SECRET,{expiresIn:"30d"})}
function auth(req,res,next){const t=(req.headers.authorization||"").replace("Bearer ","");if(!t)return res.status(401).json({error:"Please log in first."});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch{return res.status(401).json({error:"Session expired. Please log in again."})}}
function dayKey(d=new Date()){return d.toISOString().slice(0,10)}
function subjectCounts(p){const c={};for(const x of p)c[x.subject||"Study"]=(c[x.subject||"Study"]||0)+1;return c}
function studyStreak(p){const days=new Set(p.map(x=>String(x.createdAt||"").slice(0,10)));let s=0,d=new Date();while(days.has(dayKey(d))){s++;d.setDate(d.getDate()-1)}return s}
function badges(p,st,uploads){const b=[];if(p.length>=1)b.push("First Study Session");if(p.length>=5)b.push("5 Tasks Complete");if(p.length>=20)b.push("Study Machine");if(st>=3)b.push("3-Day Streak");if(st>=7)b.push("7-Day Streak");if((uploads||[]).length>=1)b.push("Homework Uploaded");return b}
function memoryText(db,userId){const m=db.memories.filter(x=>x.userId===userId).slice(-10);return m.length?m.map(x=>`- ${x.subject}: ${x.note}`).join("\n"):"No stored learning memory yet."}
function updateMemory(db,userId,subject,msg){const l=String(msg).toLowerCase();let note="Studied "+subject+".";if(l.includes("fraction"))note="Needs help with fractions.";else if(l.includes("essay"))note="Practises essay structure.";else if(l.includes("algebra"))note="Practises algebra steps.";else if(l.includes("photosynthesis"))note="Practises photosynthesis.";else if(l.includes("homework")||l.includes("photo"))note="Uses homework help.";db.memories.push({id:id(),userId,subject,note,createdAt:new Date().toISOString()})}
function extractOpenAIText(data){if(data.output_text)return data.output_text;if(Array.isArray(data.output)){for(const item of data.output){if(Array.isArray(item.content)){for(const c of item.content){if(typeof c.text==="string")return c.text;if(c.text&&typeof c.text.value==="string")return c.text.value}}}}return""}
async function askAI({message,subject,yearLevel,country,memory}){if(!OPENAI_API_KEY||OPENAI_API_KEY.includes("put_")||OPENAI_API_KEY.length<20)return{mode:"demo",answer:`Demo mode answer for ${yearLevel} ${subject}:\n\nYou asked: "${message}"\n\nLive AI is not connected yet.\n\nStudent memory:\n${memory}\n\nPractice question: Can you explain the main idea back in your own words?`};const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),25000);const system=`You are StudyCoach AI, a safe friendly tutor. Country: ${country}. Year: ${yearLevel}. Subject: ${subject}.\nStudent memory:\n${memory}\nTeach step-by-step. Give one example, one practice question, and one next study step. Do not just give final homework answers.`;try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",signal:controller.signal,headers:{"Authorization":`Bearer ${OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:OPENAI_MODEL,input:[{role:"system",content:system},{role:"user",content:message}]})});clearTimeout(timeout);const data=await r.json().catch(()=>({}));if(!r.ok)return{mode:"error",answer:"AI error: "+(data.error?.message||`OpenAI API error ${r.status}`)};const text=extractOpenAIText(data);return{mode:"live",answer:text||"The AI returned no answer. Try again."}}catch(e){clearTimeout(timeout);return{mode:"error",answer:e.name==="AbortError"?"AI timeout: the AI took too long to reply. Try again.":"AI connection error: "+e.message}}}
app.get("/api/health",(req,res)=>res.json({ok:true,app:"StudyCoach AI Final App Store Starter",time:new Date().toISOString(),hasOpenAIKey:Boolean(OPENAI_API_KEY&&OPENAI_API_KEY.length>20&&!OPENAI_API_KEY.includes("put_")),model:OPENAI_MODEL,databaseFileExists:fs.existsSync(DB_PATH)}));
app.post("/api/signup",async(req,res)=>{const db=readDb(),{name,email,password,yearLevel,country,role}=req.body;if(!name||!email||!password)return res.status(400).json({error:"Name, email and password are required."});if(String(password).length<6)return res.status(400).json({error:"Password must be at least 6 characters."});const clean=String(email).toLowerCase().trim();if(db.users.find(u=>u.email===clean))return res.status(400).json({error:"Email already used. Try login instead."});const u={id:id(),name:String(name).trim(),email:clean,passwordHash:await bcrypt.hash(password,10),yearLevel:yearLevel||"Year 7",country:country||"New Zealand",role:role||"student",plan:"free",createdAt:new Date().toISOString()};db.users.push(u);writeDb(db);res.json({token:tokenFor(u),user:safeUser(u)})});
app.post("/api/login",async(req,res)=>{const db=readDb(),u=db.users.find(x=>x.email===String(req.body.email||"").toLowerCase().trim());if(!u||!(await bcrypt.compare(req.body.password||"",u.passwordHash)))return res.status(401).json({error:"Wrong email or password."});res.json({token:tokenFor(u),user:safeUser(u)})});
app.get("/api/me",auth,(req,res)=>{const db=readDb();res.json({user:safeUser(db.users.find(u=>u.id===req.user.id))})});
app.post("/api/chat",auth,async(req,res)=>{const db=readDb(),u=db.users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:"User not found."});const {message,subject,yearLevel,country}=req.body;if(!message)return res.status(400).json({error:"Message required."});const sub=subject||"Study",yr=yearLevel||u.yearLevel||"Year 7",ct=country||u.country||"New Zealand",mem=memoryText(db,u.id),result=await askAI({message,subject:sub,yearLevel:yr,country:ct,memory:mem}),now=new Date().toISOString();db.chats.push({id:id(),userId:u.id,message,answer:result.answer,mode:result.mode,subject:sub,yearLevel:yr,country:ct,createdAt:now});db.progress.push({id:id(),userId:u.id,type:"chat",subject:sub,title:message.slice(0,80),createdAt:now});updateMemory(db,u.id,sub,message);writeDb(db);res.json({answer:result.answer,mode:result.mode})});
app.get("/api/history",auth,(req,res)=>{const db=readDb();res.json({chats:db.chats.filter(c=>c.userId===req.user.id).slice(-50).reverse()})});
app.get("/api/progress",auth,(req,res)=>{const db=readDb(),p=db.progress.filter(x=>x.userId===req.user.id),up=db.uploads.filter(x=>x.userId===req.user.id),st=studyStreak(p),mem=db.memories.filter(x=>x.userId===req.user.id).slice(-10).reverse(),joined=mem.map(x=>x.note.toLowerCase()).join(" "),weak=[];if(joined.includes("fraction"))weak.push("Fractions");if(joined.includes("essay"))weak.push("Essay structure");if(joined.includes("algebra"))weak.push("Algebra");if(joined.includes("photosynthesis"))weak.push("Photosynthesis");if(!weak.length)weak.push("Revision consistency");res.json({total:p.length,bySubject:subjectCounts(p),streak:st,badges:badges(p,st,up),weakAreas:weak,recent:p.slice(-10).reverse(),memories:mem,uploads:up.slice(-10).reverse()})});
app.post("/api/study-plan",auth,(req,res)=>{const db=readDb(),goal=req.body.goal||`Improve at ${req.body.subject||"Study"}`,sub=req.body.subject||"Study",n=Math.min(Math.max(Number(req.body.days||7),3),14),days=[];for(let i=1;i<=n;i++)days.push({day:i,task:i===1?`Learn the basics of ${goal}`:i===n?`Final review and mini test for ${goal}`:`Practise ${sub} for 15 minutes and review mistakes`,minutes:i===n?30:15});const plan={id:id(),userId:req.user.id,goal,subject:sub,days,createdAt:new Date().toISOString()};db.plans.push(plan);db.progress.push({id:id(),userId:req.user.id,type:"plan",subject:sub,title:goal,createdAt:new Date().toISOString()});writeDb(db);res.json({plan})});
app.post("/api/quiz",auth,(req,res)=>{const db=readDb(),t=req.body.topic||"your topic",sub=req.body.subject||"Study",quiz={id:id(),userId:req.user.id,topic:t,subject:sub,questions:[`What is the main idea of ${t}?`,`Give one example of ${t}.`,`What is one common mistake with ${t}?`,`Explain ${t} in your own words.`,`Create your own practice question about ${t}.`],createdAt:new Date().toISOString()};db.quizzes.push(quiz);db.progress.push({id:id(),userId:req.user.id,type:"quiz",subject:sub,title:t,createdAt:new Date().toISOString()});writeDb(db);res.json({quiz})});
app.post("/api/flashcards",auth,(req,res)=>{const db=readDb(),t=req.body.topic||"your topic",sub=req.body.subject||"Study",flash={id:id(),userId:req.user.id,topic:t,subject:sub,cards:[{front:"Definition",back:`What does ${t} mean?`},{front:"Example",back:`Give one example of ${t}.`},{front:"Mistake",back:`What should you avoid when learning ${t}?`},{front:"Memory tip",back:`How can you remember ${t}?`}],createdAt:new Date().toISOString()};db.flashcards.push(flash);db.progress.push({id:id(),userId:req.user.id,type:"flashcards",subject:sub,title:t,createdAt:new Date().toISOString()});writeDb(db);res.json({flashcards:flash})});
app.post("/api/upload-homework",auth,upload.single("homework"),(req,res)=>{const db=readDb();if(!req.file)return res.status(400).json({error:"No file uploaded."});const rec={id:id(),userId:req.user.id,originalName:req.file.originalname,filename:req.file.filename,mimeType:req.file.mimetype,size:req.file.size,note:req.body.note||"",createdAt:new Date().toISOString()};db.uploads.push(rec);db.progress.push({id:id(),userId:req.user.id,type:"upload",subject:"Homework",title:req.file.originalname,createdAt:new Date().toISOString()});db.memories.push({id:id(),userId:req.user.id,subject:"Homework",note:"Uploaded homework/photo for help.",createdAt:new Date().toISOString()});writeDb(db);res.json({upload:rec,message:"Homework uploaded. Real image reading can be connected next with a vision model."})});
app.get("/api/teacher-summary",auth,(req,res)=>{const db=readDb();res.json({students:db.users.map(u=>{const p=db.progress.filter(x=>x.userId===u.id);return{name:u.name,yearLevel:u.yearLevel,tasks:p.length,streak:studyStreak(p),role:u.role||"student"}})})});
app.post("/api/fake-upgrade",auth,(req,res)=>{const db=readDb(),u=db.users.find(x=>x.id===req.user.id);if(u)u.plan="premium";writeDb(db);res.json({ok:true,message:"Demo upgraded to premium. Stripe can be connected next."})});
ensureDb();app.listen(PORT,()=>{console.log(`StudyCoach AI Final App Store Starter running at http://localhost:${PORT}`);console.log(`Debug health check: http://localhost:${PORT}/api/health`);console.log(`OpenAI key found: ${Boolean(OPENAI_API_KEY&&OPENAI_API_KEY.length>20&&!OPENAI_API_KEY.includes("put_"))}`)});
