
require("dotenv").config();
const express=require("express"),cors=require("cors"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),fs=require("fs"),path=require("path"),crypto=require("crypto"),multer=require("multer"),Stripe=require("stripe");
const app=express(),PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET||"change-this-secret",OPENAI_API_KEY=process.env.OPENAI_API_KEY||"",OPENAI_MODEL=process.env.OPENAI_MODEL||"gpt-4.1-mini",STRIPE_SECRET_KEY=process.env.STRIPE_SECRET_KEY||"",STRIPE_PRICE_ID=process.env.STRIPE_PRICE_ID||"",APP_URL=process.env.APP_URL||`http://localhost:${PORT}`;
const stripe=STRIPE_SECRET_KEY?new Stripe(STRIPE_SECRET_KEY):null,DB_PATH=path.join(__dirname,"data","db.json"),UPLOAD_DIR=path.join(__dirname,"data","uploads"),upload=multer({dest:UPLOAD_DIR});
app.use(cors());app.use(express.json({limit:"10mb"}));app.use(express.static(path.join(__dirname,"public")));
function id(){return crypto.randomUUID?crypto.randomUUID():crypto.randomBytes(16).toString("hex")}
function ensureDb(){if(!fs.existsSync(path.dirname(DB_PATH)))fs.mkdirSync(path.dirname(DB_PATH),{recursive:true});if(!fs.existsSync(UPLOAD_DIR))fs.mkdirSync(UPLOAD_DIR,{recursive:true});if(!fs.existsSync(DB_PATH))fs.writeFileSync(DB_PATH,JSON.stringify({users:[],chats:[],progress:[],plans:[],quizzes:[],flashcards:[],uploads:[],memories:[],payments:[]},null,2))}
function readDb(){ensureDb();try{let db=JSON.parse(fs.readFileSync(DB_PATH,"utf8"));["users","chats","progress","plans","quizzes","flashcards","uploads","memories","payments"].forEach(k=>db[k]||=[]);return db}catch{return{users:[],chats:[],progress:[],plans:[],quizzes:[],flashcards:[],uploads:[],memories:[],payments:[]}}}
function writeDb(db){fs.writeFileSync(DB_PATH,JSON.stringify(db,null,2))}
function safeUser(u){if(!u)return null;const{passwordHash,...s}=u;return s}
function tokenFor(u){return jwt.sign({id:u.id,email:u.email},JWT_SECRET,{expiresIn:"30d"})}
function auth(req,res,next){const t=(req.headers.authorization||"").replace("Bearer ","");if(!t)return res.status(401).json({error:"Please log in first."});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch{return res.status(401).json({error:"Session expired. Please log in again."})}}
function dayKey(d=new Date()){return d.toISOString().slice(0,10)}
function subjectCounts(p){const c={};for(const x of p)c[x.subject||"Study"]=(c[x.subject||"Study"]||0)+1;return c}
function studyStreak(p){const days=new Set(p.map(x=>String(x.createdAt||"").slice(0,10)));let s=0,d=new Date();while(days.has(dayKey(d))){s++;d.setDate(d.getDate()-1)}return s}
function badges(p,st,up){let b=[];if(p.length>=1)b.push("First Study Session");if(p.length>=5)b.push("5 Tasks Complete");if(st>=3)b.push("3-Day Streak");if((up||[]).length>=1)b.push("Homework Uploaded");return b}
function memoryText(db,userId){const m=db.memories.filter(x=>x.userId===userId).slice(-10);return m.length?m.map(x=>`- ${x.subject}: ${x.note}`).join("\n"):"No stored learning memory yet."}
function updateMemory(db,userId,subject,msg){const l=String(msg).toLowerCase();let note="Studied "+subject+".";if(l.includes("fraction"))note="Needs help with fractions.";else if(l.includes("essay"))note="Practises essay structure.";else if(l.includes("algebra"))note="Practises algebra.";else if(l.includes("photosynthesis"))note="Practises photosynthesis.";db.memories.push({id:id(),userId,subject,note,createdAt:new Date().toISOString()})}
function extractText(data){if(data.output_text)return data.output_text;if(Array.isArray(data.output)){for(const item of data.output){if(Array.isArray(item.content)){for(const c of item.content){if(typeof c.text==="string")return c.text;if(c.text&&typeof c.text.value==="string")return c.text.value}}}}return""}
async function askAI({message,subject,yearLevel,country,memory}){if(!OPENAI_API_KEY||OPENAI_API_KEY.includes("put_")||OPENAI_API_KEY.length<20)return{mode:"demo",answer:`Demo answer for ${yearLevel} ${subject}.\n\nYou asked: ${message}\n\nConnect OpenAI to get live AI.`};const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),25000);const system=`You are StudyCoach AI, a friendly tutor. Country: ${country}. Year: ${yearLevel}. Subject: ${subject}.\nMemory:\n${memory}\nTeach step by step, give one example and one practice question.`;try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",signal:controller.signal,headers:{"Authorization":`Bearer ${OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:OPENAI_MODEL,input:[{role:"system",content:system},{role:"user",content:message}]})});clearTimeout(timeout);const data=await r.json().catch(()=>({}));if(!r.ok)return{mode:"error",answer:"AI error: "+(data.error?.message||`OpenAI API error ${r.status}`)};return{mode:"live",answer:extractText(data)||"The AI returned no answer. Try again."}}catch(e){clearTimeout(timeout);return{mode:"error",answer:e.name==="AbortError"?"AI timeout. Try again.":"AI connection error: "+e.message}}}
app.get("/api/health",(req,res)=>res.json({ok:true,app:"StudyCoach AI 7 Stripe",hasOpenAIKey:Boolean(OPENAI_API_KEY&&OPENAI_API_KEY.length>20&&!OPENAI_API_KEY.includes("put_")),hasStripeSecretKey:Boolean(STRIPE_SECRET_KEY&&STRIPE_SECRET_KEY.length>20),hasStripePriceId:Boolean(STRIPE_PRICE_ID&&STRIPE_PRICE_ID.startsWith("price_")),appUrl:APP_URL}));
app.post("/api/signup",async(req,res)=>{const db=readDb(),{name,email,password,yearLevel,country}=req.body;if(!name||!email||!password)return res.status(400).json({error:"Name, email and password are required."});if(String(password).length<6)return res.status(400).json({error:"Password must be at least 6 characters."});const clean=String(email).toLowerCase().trim();if(db.users.find(u=>u.email===clean))return res.status(400).json({error:"Email already used. Try login instead."});const u={id:id(),name:String(name).trim(),email:clean,passwordHash:await bcrypt.hash(password,10),yearLevel:yearLevel||"Year 7",country:country||"New Zealand",role:"student",plan:"free",stripeCustomerId:"",stripeSubscriptionId:"",createdAt:new Date().toISOString()};db.users.push(u);writeDb(db);res.json({token:tokenFor(u),user:safeUser(u)})});
app.post("/api/login",async(req,res)=>{const db=readDb(),u=db.users.find(x=>x.email===String(req.body.email||"").toLowerCase().trim());if(!u||!(await bcrypt.compare(req.body.password||"",u.passwordHash)))return res.status(401).json({error:"Wrong email or password."});res.json({token:tokenFor(u),user:safeUser(u)})});
app.get("/api/me",auth,(req,res)=>{const db=readDb();res.json({user:safeUser(db.users.find(u=>u.id===req.user.id))})});
app.post("/api/chat",auth,async(req,res)=>{const db=readDb(),u=db.users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:"User not found."});const {message,subject,yearLevel,country}=req.body;if(!message)return res.status(400).json({error:"Message required."});const sub=subject||"Study",yr=yearLevel||u.yearLevel||"Year 7",ct=country||u.country||"New Zealand",mem=memoryText(db,u.id),result=await askAI({message,subject:sub,yearLevel:yr,country:ct,memory:mem}),now=new Date().toISOString();db.chats.push({id:id(),userId:u.id,message,answer:result.answer,mode:result.mode,subject:sub,createdAt:now});db.progress.push({id:id(),userId:u.id,type:"chat",subject:sub,title:message.slice(0,80),createdAt:now});updateMemory(db,u.id,sub,message);writeDb(db);res.json({answer:result.answer,mode:result.mode})});
app.get("/api/history",auth,(req,res)=>{const db=readDb();res.json({chats:db.chats.filter(c=>c.userId===req.user.id).slice(-50).reverse()})});
app.get("/api/progress",auth,(req,res)=>{const db=readDb(),p=db.progress.filter(x=>x.userId===req.user.id),up=db.uploads.filter(x=>x.userId===req.user.id),st=studyStreak(p),mem=db.memories.filter(x=>x.userId===req.user.id).slice(-10).reverse();res.json({total:p.length,bySubject:subjectCounts(p),streak:st,badges:badges(p,st,up),weakAreas:["Revision consistency"],recent:p.slice(-10).reverse(),memories:mem,uploads:up.slice(-10).reverse()})});
app.post("/api/study-plan",auth,(req,res)=>{const db=readDb(),goal=req.body.goal||"Improve this week",sub=req.body.subject||"Study",n=Math.min(Math.max(Number(req.body.days||7),3),14),days=[];for(let i=1;i<=n;i++)days.push({day:i,task:i===1?`Learn the basics of ${goal}`:i===n?`Final review for ${goal}`:`Practise ${sub} for 15 minutes`,minutes:i===n?30:15});const plan={id:id(),userId:req.user.id,goal,subject:sub,days,createdAt:new Date().toISOString()};db.plans.push(plan);db.progress.push({id:id(),userId:req.user.id,type:"plan",subject:sub,title:goal,createdAt:new Date().toISOString()});writeDb(db);res.json({plan})});
app.post("/api/quiz",auth,(req,res)=>{const db=readDb(),t=req.body.topic||"your topic",sub=req.body.subject||"Study",quiz={id:id(),userId:req.user.id,topic:t,subject:sub,questions:[`What is ${t}?`,`Give one example of ${t}.`,`What is one mistake with ${t}?`,`Explain ${t} in your words.`,`Create a question about ${t}.`],createdAt:new Date().toISOString()};db.quizzes.push(quiz);db.progress.push({id:id(),userId:req.user.id,type:"quiz",subject:sub,title:t,createdAt:new Date().toISOString()});writeDb(db);res.json({quiz})});
app.post("/api/flashcards",auth,(req,res)=>{const db=readDb(),t=req.body.topic||"your topic",sub=req.body.subject||"Study",flash={id:id(),userId:req.user.id,topic:t,subject:sub,cards:[{front:"Definition",back:`What does ${t} mean?`},{front:"Example",back:`Give one example of ${t}.`},{front:"Mistake",back:`What should you avoid with ${t}?`}],createdAt:new Date().toISOString()};db.flashcards.push(flash);db.progress.push({id:id(),userId:req.user.id,type:"flashcards",subject:sub,title:t,createdAt:new Date().toISOString()});writeDb(db);res.json({flashcards:flash})});
app.post("/api/upload-homework",auth,upload.single("homework"),(req,res)=>{const db=readDb();if(!req.file)return res.status(400).json({error:"No file uploaded."});const rec={id:id(),userId:req.user.id,originalName:req.file.originalname,filename:req.file.filename,mimeType:req.file.mimetype,size:req.file.size,note:req.body.note||"",createdAt:new Date().toISOString()};db.uploads.push(rec);db.progress.push({id:id(),userId:req.user.id,type:"upload",subject:"Homework",title:req.file.originalname,createdAt:new Date().toISOString()});writeDb(db);res.json({upload:rec,message:"Homework uploaded."})});
app.get("/api/teacher-summary",auth,(req,res)=>{const db=readDb();res.json({students:db.users.map(u=>{const p=db.progress.filter(x=>x.userId===u.id);return{name:u.name,yearLevel:u.yearLevel,tasks:p.length,streak:studyStreak(p),plan:u.plan||"free"}})})});
app.post("/api/create-checkout-session",auth,async(req,res)=>{if(!stripe)return res.status(500).json({error:"Stripe secret key is missing."});if(!STRIPE_PRICE_ID||!STRIPE_PRICE_ID.startsWith("price_"))return res.status(500).json({error:"Stripe price ID is missing."});const db=readDb(),u=db.users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:"User not found."});try{let customerId=u.stripeCustomerId;if(!customerId){const customer=await stripe.customers.create({email:u.email,name:u.name,metadata:{userId:u.id}});customerId=customer.id;u.stripeCustomerId=customerId;writeDb(db)}const session=await stripe.checkout.sessions.create({mode:"subscription",customer:customerId,line_items:[{price:STRIPE_PRICE_ID,quantity:1}],success_url:`${APP_URL}/success.html`,cancel_url:`${APP_URL}/cancel.html`,metadata:{userId:u.id}});res.json({url:session.url})}catch(e){res.status(500).json({error:"Stripe checkout error: "+e.message})}});
ensureDb();app.listen(PORT,()=>{console.log(`StudyCoach AI 7 Stripe running at http://localhost:${PORT}`);console.log(`OpenAI key found: ${Boolean(OPENAI_API_KEY&&OPENAI_API_KEY.length>20&&!OPENAI_API_KEY.includes("put_"))}`);console.log(`Stripe secret found: ${Boolean(STRIPE_SECRET_KEY&&STRIPE_SECRET_KEY.length>20)}`);console.log(`Stripe price found: ${Boolean(STRIPE_PRICE_ID&&STRIPE_PRICE_ID.startsWith("price_"))}`)});
